SET DATABASE SQL SYNTAX MYS TRUE;

CREATE TABLE acl_class
( 
    id BIGINT NOT NULL IDENTITY,
    class VARCHAR (255) NULL,
);

CREATE TABLE acl_sid
(
    id BIGINT NOT NULL IDENTITY,
    principal TINYINT NOT NULL,
    sid VARCHAR(100) NOT NULL,
    CONSTRAINT uk_acl_sid UNIQUE (sid, principal)
);

CREATE TABLE base_components 
(
    COMPONENT_TYPE VARCHAR(20) NOT NULL,
    PRIMARY KEY (COMPONENT_TYPE)
);

CREATE TABLE common_schema_version
(
    version VARCHAR (20) NOT NULL,
    description VARCHAR (100) NULL,
    type VARCHAR (10) NOT NULL,
    script VARCHAR (200) NOT NULL,
    checksum INT NULL,
    installed_by VARCHAR (30) NOT NULL,
    installed_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    execution_time INT NULL,
    state VARCHAR (15) NOT NULL,
    current_version TINYINT NOT NULL,
    PRIMARY KEY (version)
);

CREATE TABLE components 
(
    CMP_ID BIGINT NOT NULL IDENTITY,
    COMPONENT_TYPE VARCHAR (255) NOT NULL,
    UUID VARCHAR (255) NOT NULL,
    NAME VARCHAR (255) NOT NULL,
    DESCRIPTION VARCHAR (255) NULL,
);

CREATE TABLE groups 
(
    GROUP_ID BIGINT NOT NULL IDENTITY,
    UUID VARCHAR (255) NOT NULL,
    NAME VARCHAR (255) NOT NULL,
    DESCRIPTION VARCHAR (255) NULL
);

CREATE TABLE persistent_logins 
(
    username VARCHAR (64) NOT NULL,
    series VARCHAR (64) NOT NULL,
    token VARCHAR (64) NOT NULL,
    last_used TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (series)
);

CREATE TABLE poulpe_schema_version
(
    version VARCHAR (20) NOT NULL,
    description VARCHAR (100) NULL,
    type VARCHAR (10) NOT NULL,
    script VARCHAR (200) NOT NULL,
    checksum INT NULL,
    installed_by VARCHAR (30) NOT NULL,
    installed_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    execution_time INT NULL,
    state VARCHAR (15) NOT NULL,
    current_version TINYINT NOT NULL,
    PRIMARY KEY (version)
);

CREATE TABLE ranks 
(
    RANK_ID BIGINT NOT NULL IDENTITY,
    UUID VARCHAR (255) NOT NULL,
    RANK_NAME VARCHAR (255) NOT NULL,
    AUTO_ASSIGNED TINYINT NULL,
    POST_COUNT INT NULL
);

CREATE TABLE sections
(
    SECTION_ID BIGINT NOT NULL IDENTITY,
    UUID VARCHAR (255) NOT NULL,
    NAME VARCHAR (255) NOT NULL,
    DESCRIPTION VARCHAR (255) NULL,
    POSITION INT NULL,
    COMPONENT_ID BIGINT NULL
);

CREATE TABLE topic_types
(
    ID BIGINT NOT NULL IDENTITY,
    UUID VARCHAR (255) NOT NULL,
    TITLE VARCHAR (255) NOT NULL,
    DESCRIPTION VARCHAR (255) NULL
);

CREATE TABLE users
(
    ID BIGINT NOT NULL IDENTITY,
    UUID VARCHAR (255) NOT NULL,
    FIRST_NAME VARCHAR (255) NULL,
    LAST_NAME VARCHAR (255) NULL,
    USERNAME VARCHAR (255) NOT NULL,
    ENCODED_USERNAME VARCHAR (255) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    PASSWORD VARCHAR (255) NOT NULL,
    ROLE VARCHAR (255) NULL,
    LAST_LOGIN TIMESTAMP NULL,
    AVATAR BLOB NULL,
    BAN_REASON LONGVARCHAR NULL,
    SALT VARCHAR (64) NOT NULL,
    REGISTRATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UUID UNIQUE(UUID),
    CONSTRAINT USERNAME UNIQUE(USERNAME),
    CONSTRAINT EMAIL UNIQUE(EMAIL),
);

CREATE TABLE acl_object_identity
(
    id BIGINT NOT NULL IDENTITY,
    object_id_class BIGINT NOT NULL,
    object_id_identity BIGINT NOT NULL,
    parent_object BIGINT NULL,
    owner_sid BIGINT NULL,
    entries_inheriting TINYINT NOT NULL,
    CONSTRAINT fk_acl_obj_class FOREIGN KEY (object_id_class) REFERENCES acl_class (id),
    CONSTRAINT fk_acl_obj_owner FOREIGN KEY (owner_sid) REFERENCES acl_sid (id),
    CONSTRAINT fk_acl_obj_parent FOREIGN KEY (parent_object) REFERENCES acl_object_identity (id)
);

CREATE TABLE acl_entry
(
    id BIGINT NOT NULL IDENTITY,
    acl_object_identity BIGINT NOT NULL,
    ace_order INT NOT NULL,
    sid BIGINT NOT NULL,
    mask INT NOT NULL,
    granting TINYINT NOT NULL,
    audit_success TINYINT NOT NULL,
    audit_failure TINYINT NOT NULL,
    CONSTRAINT fk_acl_entry_obj_id FOREIGN KEY (acl_object_identity) REFERENCES acl_object_identity (id),
    CONSTRAINT fk_acl_entry_sid FOREIGN KEY (sid) REFERENCES acl_sid (id)
);

CREATE TABLE branches
(
    BRANCH_ID BIGINT NOT NULL IDENTITY,
    UUID VARCHAR (255) NOT NULL,
    NAME VARCHAR (255) NOT NULL,
    DESCRIPTION VARCHAR (512) NULL,
    POSITION INT NULL,
    SECTION_ID BIGINT NULL,
    MODERATORS_GROUP_ID BIGINT NULL,
    
    CONSTRAINT FK_MODERATORS_GROUP_ID FOREIGN KEY (MODERATORS_GROUP_ID) REFERENCES groups (GROUP_ID),
    CONSTRAINT FK_SECTION FOREIGN KEY (SECTION_ID) REFERENCES sections (SECTION_ID)
);

CREATE TABLE default_properties
(
    PROPERTY_ID BIGINT NOT NULL IDENTITY,
    UUID VARCHAR (255) NOT NULL,
    BASE_COMPONENT_TYPE VARCHAR (20) NULL,
    NAME VARCHAR (255) NOT NULL,
    VALUE VARCHAR (255) NULL,
    VALIDATION_RULE VARCHAR (255) NOT NULL,
    CONSTRAINT FK_BASE_COMPONENT FOREIGN KEY (BASE_COMPONENT_TYPE) REFERENCES base_components (COMPONENT_TYPE)
);

CREATE TABLE group_user_ref 
(
    GROUP_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CONSTRAINT FK556C5FDF4ECBCAA4 FOREIGN KEY (USER_ID) REFERENCES users (ID),
    CONSTRAINT FK556C5FDFB7F395D0 FOREIGN KEY (GROUP_ID) REFERENCES groups (GROUP_ID)
);

CREATE TABLE properties
(
    PROPERTY_ID BIGINT NOT NULL IDENTITY,
    UUID VARCHAR (255) NOT NULL,
    NAME VARCHAR (255) NOT NULL,
    VALUE VARCHAR (255) NULL,
    CMP_ID BIGINT NULL,
    VALIDATION_RULE VARCHAR (255) NOT NULL,
    CONSTRAINT FK_COMPONENT FOREIGN KEY (CMP_ID) REFERENCES components (CMP_ID)
);
