//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.26 at 01:12:36 PM MSK 
//


package org.jtalks.poulpe.web.controller.rest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for authentication complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authentication">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="credintals" type="{http://www.jtalks.org/namespaces/1.0}credintals"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="statusInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="profile" type="{http://www.jtalks.org/namespaces/1.0}profile" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authentication", namespace = "http://www.jtalks.org/namespaces/1.0", propOrder = {
    "credintals",
    "status",
    "statusInfo",
    "profile"
})
@XmlRootElement(name = "authentication", namespace = "http://www.jtalks.org/namespaces/1.0")
public class Authentication {

    @XmlElement(namespace = "http://www.jtalks.org/namespaces/1.0", required = true)
    protected Credintals credintals;
    @XmlElement(namespace = "http://www.jtalks.org/namespaces/1.0")
    protected String status;
    @XmlElement(namespace = "http://www.jtalks.org/namespaces/1.0")
    protected String statusInfo;
    @XmlElement(namespace = "http://www.jtalks.org/namespaces/1.0")
    protected Profile profile;

    /**
     * Gets the value of the credintals property.
     * 
     * @return
     *     possible object is
     *     {@link Credintals }
     *     
     */
    public Credintals getCredintals() {
        return credintals;
    }

    /**
     * Sets the value of the credintals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Credintals }
     *     
     */
    public void setCredintals(Credintals value) {
        this.credintals = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the statusInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusInfo() {
        return statusInfo;
    }

    /**
     * Sets the value of the statusInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusInfo(String value) {
        this.statusInfo = value;
    }

    /**
     * Gets the value of the profile property.
     * 
     * @return
     *     possible object is
     *     {@link Profile }
     *     
     */
    public Profile getProfile() {
        return profile;
    }

    /**
     * Sets the value of the profile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Profile }
     *     
     */
    public void setProfile(Profile value) {
        this.profile = value;
    }

}
